# Generated by Django 4.1.5 on 2023-03-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-time_posted"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="header",
            field=models.TextField(max_length=100),
        ),
    ]
