# Generated by Django 4.1.5 on 2023-03-19 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_post_options_alter_post_header"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time_posted",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.localtime
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.localtime
            ),
        ),
    ]
